version: 2

sources:
  - name: bronze
    database: DBT_HOL_DEV
    schema: BRONZE
    quoting:
      database: false
      schema: false
      identifier: true  # Ensures Snowflake upper/lowercase consistency
    freshness:
      warn_after: {count: 12, period: hour}  # Warn if >12h stale
      error_after: {count: 24, period: hour} # Error if >24h stale
    loaded_at_field: updated_at  # Assuming your tables have this

    tables:
      - name: D365_CUSTOMERS
        description: "External table for D365 customer data from ADLS"
        columns:
          - name: customer_id
            description: "Unique identifier for each customer"
            tests:
              - unique
              - not_null
          - name: first_name
            description: "Customer's first name"
            tests:
              - not_null
          - name: last_name
            description: "Customer's last name"
            tests:
              - not_null
          - name: email
            description: "Customer's email address"
            tests:
              - not_null
              - unique
          - name: postal_code
            description: "Customer's postal code for location-based analysis"
            tests:
              - not_null
          - name: region
            description: "Customer's region/state"
            tests:
              - not_null
          - name: created_at
            description: "Timestamp when customer record was created"
            tests:
              - not_null
          - name: updated_at
            description: "Timestamp when customer record was last updated"
            tests:
              - not_null
      - name: EXCEL_DATA
        description: "External table for Legacy Excel customer data"
        columns:
          - name: customer_id
            description: "Unique identifier for each customer"
            tests:
              - unique
              - not_null
          - name: first_name
            description: "Customer's first name"
            tests:
              - not_null
          - name: last_name
            description: "Customer's last name"
            tests:
              - not_null
          - name: email
            description: "Customer's email address"
            tests:
              - not_null
              - unique
          - name: postal_code
            description: "Customer's postal code for location-based analysis"
            tests:
              - not_null
          - name: region
            description: "Customer's region/state"
            tests:
              - not_null

  - name: marketplace
    database: WEATHER_SOURCE_LLC_FROSTBYTE
    schema: ONPOINT_ID
    quoting:
      database: false
      schema: false
      identifier: false
    tables:
      - name: forecast_day
        description: "Weather forecast data from Snowflake Marketplace"
        columns:
          - name: postal_code
            description: "Postal code for weather location"
            tests:
              - not_null
          - name: country
            description: "Country code"
            tests:
              - not_null
          - name: date_valid_std
            description: "Date for weather forecast"
            tests:
              - not_null
          - name: avg_temperature_air_2m_f
            description: "Average temperature in Fahrenheit"
            tests:
              - not_null
          - name: avg_humidity_relative_2m_pct
            description: "Average humidity percentage"
            tests:
              - not_null
          - name: avg_wind_speed_10m_mph
            description: "Average wind speed in mph"
            tests:
              - not_null
          - name: tot_precipitation_in
            description: "Total precipitation in inches"
            tests:
              - not_null
          - name: tot_snowfall_in
            description: "Total snowfall in inches"
            tests:
              - not_null
          - name: avg_cloud_cover_tot_pct
            description: "Average cloud cover percentage"
            tests:
              - not_null
          - name: probability_of_precipitation_pct
            description: "Probability of precipitation percentage"
            tests:
              - not_null
          - name: probability_of_snow_pct
            description: "Probability of snow percentage"
            tests:
              - not_null

models:
  - name: bronze_customers
    description: "Bronze layer view for D365 customer data with minimal transformations"
    columns:
      - name: customer_id
        description: "Unique identifier for each customer"
        tests:
          - unique
          - not_null
      - name: first_name
        description: "Customer's first name"
        tests:
          - not_null
      - name: last_name
        description: "Customer's last name"
        tests:
          - not_null
      - name: email
        description: "Customer's email address"
        tests:
          - not_null
          - unique
      - name: postal_code
        description: "Customer's postal code for location-based analysis"
        tests:
          - not_null
      - name: region
        description: "Customer's region/state"
        tests:
          - not_null
      - name: created_at
        description: "Timestamp when customer record was created"
        tests:
          - not_null
      - name: updated_at
        description: "Timestamp when customer record was last updated"
        tests:
          - not_null

  - name: bronze_legacy_customers
    description: "Bronze layer view for legacy Excel customer data with minimal transformations"
    columns:
      - name: customer_id
        description: "Unique identifier for each customer"
        tests:
          - unique
          - not_null
      - name: first_name
        description: "Customer's first name"
        tests:
          - not_null
      - name: last_name
        description: "Customer's last name"
        tests:
          - not_null
      - name: email
        description: "Customer's email address"
        tests:
          - not_null
          - unique
      - name: postal_code
        description: "Customer's postal code for location-based analysis"
        tests:
          - not_null
      - name: region
        description: "Customer's region/state"
        tests:
          - not_null

  - name: bronze_weather
    description: "Bronze layer view for weather forecast data from Snowflake Marketplace"
    columns:
      - name: postal_code
        description: "Postal code for weather location"
        tests:
          - not_null
      - name: country
        description: "Country code"
        tests:
          - not_null
      - name: date_valid_std
        description: "Date for weather forecast"
        tests:
          - not_null
      - name: avg_temperature_air_2m_f
        description: "Average temperature in Fahrenheit"
        tests:
          - not_null
      - name: avg_humidity_relative_2m_pct
        description: "Average humidity percentage"
        tests:
          - not_null
      - name: avg_wind_speed_10m_mph
        description: "Average wind speed in mph"
        tests:
          - not_null
      - name: tot_precipitation_in
        description: "Total precipitation in inches"
        tests:
          - not_null
      - name: tot_snowfall_in
        description: "Total snowfall in inches"
        tests:
          - not_null
      - name: avg_cloud_cover_tot_pct
        description: "Average cloud cover percentage"
        tests:
          - not_null
      - name: probability_of_precipitation_pct
        description: "Probability of precipitation percentage"
        tests:
          - not_null
      - name: probability_of_snow_pct
        description: "Probability of snow percentage"
        tests:
          - not_null

